# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_householdinvitation_appintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appintegration',
            name='provider',
            field=models.CharField(
                choices=[
                    ('snoop', 'Snoop'),
                    ('whoop', 'Whoop'),
                    ('plaid', 'Plaid'),
                    ('truelayer', 'TrueLayer'),
                    ('manual', 'Manual Import'),
                ],
                max_length=20,
            ),
        ),
    ]
