# Generated by Django 4.2.27 on 2026-01-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_recurringtransaction_monthlynote'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date'], name='finance_tra_user_id_e81357_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='finance_tra_user_id_35643f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='finance_tra_user_id_be5f56_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account'], name='finance_tra_user_id_f167d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date', '-created_at'], name='finance_tra_date_301b50_idx'),
        ),
    ]
