# Generated by Django 4.2.27 on 2026-01-16 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_add_transaction_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Monthly Budget', max_length=100)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('primary_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('secondary_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partner_name', models.CharField(blank=True, default='Partner', max_length=100)),
                ('partner_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('saving', 'Saving'), ('investment', 'Investment')], default='expense', max_length=20)),
                ('split_type', models.CharField(choices=[('shared', 'Shared'), ('personal_primary', 'Personal (Primary)'), ('personal_partner', 'Personal (Partner)')], default='shared', max_length=20)),
                ('primary_share_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.housebudget')),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
    ]
