# Generated by Django 4.2.27 on 2026-01-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_add_house_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.IntegerField(blank=True, null=True)),
                ('line_item_name', models.CharField(blank=True, max_length=100)),
                ('change_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='finance.housebudget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['budget', '-created_at'], name='finance_bud_budget__3ac431_idx'), models.Index(fields=['user', '-created_at'], name='finance_bud_user_id_b2e31b_idx')],
            },
        ),
    ]
