# Generated by Django 4.2.27 on 2026-01-16 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_add_budget_change_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Groceries', 'Groceries'), ('Eating Out', 'Eating Out'), ('Transport', 'Transport'), ('Health & Fitness', 'Health & Fitness'), ('Shopping', 'Shopping')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_exclusions', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'category'], name='finance_cat_user_id_82ec96_idx')],
                'unique_together': {('user', 'transaction', 'category')},
            },
        ),
    ]
