# Generated by Django 4.2.27 on 2026-01-16 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_add_category_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portfolio_type', models.CharField(choices=[('isa', 'ISA'), ('jisa', 'Junior ISA'), ('pension', 'Pension'), ('gia', 'General Investment'), ('savings', 'Savings Account'), ('emergency', 'Emergency Fund'), ('other', 'Other')], max_length=20)),
                ('risk_level', models.CharField(choices=[('1', 'Level 1/5 - Very Low'), ('2', 'Level 2/5 - Low'), ('3', 'Level 3/5 - Medium'), ('4', 'Level 4/5 - Medium-High'), ('5', 'Level 5/5 - High'), ('none', 'N/A')], default='none', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('initial_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('year_start_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_value'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='finance.portfolio')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('portfolio', 'year', 'month')},
            },
        ),
    ]
