# Generated by Django 4.2.27 on 2026-01-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_portfolio_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(choices=[('GBP', '£'), ('INR', '₹'), ('USD', '$'), ('EUR', '€')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('isa', 'ISA'), ('jisa', 'Junior ISA'), ('pension', 'Pension'), ('gia', 'General Investment'), ('savings', 'Savings Account'), ('emergency', 'Emergency Fund'), ('pot', 'Pot'), ('other', 'Other')], max_length=20),
        ),
    ]
